ALTER TABLE "Ride" ADD COLUMN "tariffClass" TEXT NOT NULL DEFAULT 'ECONOMY';
ALTER TABLE "Ride" ADD COLUMN "waitingMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Ride" ADD COLUMN "stopMinutes" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Tariff" ADD COLUMN "tariffClass" TEXT;
ALTER TABLE "Tariff" ADD COLUMN "freeWaitingMinutes" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Tariff" ADD COLUMN "waitingPerMinute" INTEGER NOT NULL DEFAULT 500;
ALTER TABLE "Tariff" ADD COLUMN "stopPerMinute" INTEGER NOT NULL DEFAULT 500;

UPDATE "Tariff"
SET "tariffClass" = CASE
  WHEN LOWER("city") LIKE '%comfort%' THEN 'COMFORT'
  WHEN LOWER("city") LIKE '%premium%' THEN 'PREMIUM'
  ELSE 'ECONOMY'
END
WHERE "tariffClass" IS NULL;

ALTER TABLE "Tariff" ALTER COLUMN "tariffClass" SET NOT NULL;
ALTER TABLE "Tariff" ALTER COLUMN "city" SET DEFAULT 'Angren';
ALTER TABLE "Tariff" ALTER COLUMN "perKm" SET DEFAULT 2000;

ALTER TABLE "Tariff" DROP COLUMN "perMinute";
ALTER TABLE "Tariff" DROP COLUMN "surgeMultiplier";
